source: docs
destination: _site

plugins:
  - jekyll-include-cache
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - _pages

sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
    - slash-div
    - if-function

theme: minimal-mistakes-jekyll

title: Storytell
locale: en-GB
description: "An evening of true stories, generous listening, and good company."
next_event: far_from_home

collections:
  events:
    output: true
    permalink: /events/:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        image: /assets/images/splash.png
  - scope:
      path: ""
      type: events
    values:
      layout: event
      author_profile: false
      header:
        image: /assets/images/splash.png
