plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - _pages
remote_theme: mmistakes/minimal-mistakes@4.27.3
defaults:
  - scope:
    path: "_pages"
    type: pages
  values:
    layout: single
    author_profile: true
