plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - home.md
remote_theme: mmistakes/minimal-mistakes@4.27.3
