plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-relative-links
#   - jekyll-maps

# maps:
#   google:
#     api_key: ${{ YOUR_KEY_HERE }

relative_links:
  enabled: true
  collections: true

include:
  - _pages

remote_theme: mmistakes/minimal-mistakes@4.27.3

title: Storytell

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
